// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtxlLkEr6TLqo-mhuo15d0pHaxVRt9Xug',
    appId: '1:809723687154:web:8934fe8492608bf2b0a06b',
    messagingSenderId: '809723687154',
    projectId: 'recipeapp-d3f42',
    authDomain: 'recipeapp-d3f42.firebaseapp.com',
    storageBucket: 'recipeapp-d3f42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQTjTRVFbZz_AWyOq2OC_I9nELOvQfX-Q',
    appId: '1:809723687154:android:1f0c502c34cb8648b0a06b',
    messagingSenderId: '809723687154',
    projectId: 'recipeapp-d3f42',
    storageBucket: 'recipeapp-d3f42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GuqamLQjDmVajPe4GXsuGkEHkTctgwQ',
    appId: '1:809723687154:ios:0baf0977156cb9e6b0a06b',
    messagingSenderId: '809723687154',
    projectId: 'recipeapp-d3f42',
    storageBucket: 'recipeapp-d3f42.appspot.com',
    iosClientId: '809723687154-gh33pn0l5pe7opfiqe7l6j2pppo5fq30.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GuqamLQjDmVajPe4GXsuGkEHkTctgwQ',
    appId: '1:809723687154:ios:0baf0977156cb9e6b0a06b',
    messagingSenderId: '809723687154',
    projectId: 'recipeapp-d3f42',
    storageBucket: 'recipeapp-d3f42.appspot.com',
    iosClientId: '809723687154-gh33pn0l5pe7opfiqe7l6j2pppo5fq30.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
